### ISSUE TITLE
Only link first instance on a page

### ISSUE THREAD

**Issue by zioth** [zioth/dokuwiki-autolink4#4]
On some wikis, autolink4 produces too many links. Add an option to only link the first instance on a page, for each linked keyword. This should be fairly easy to implement, if I set a flag for each found match.

**Comment by zioth** [comment]
Fixed. Take a look at the config. You can now add a 'once' flag to force it to only link the first occurrence.

**Comment by mr-floppy** [comment]
Thanks again!

This looks very nice, and in combination with autotooltip it is a nice incentive to finally write some proper abstracts :)

I have found 2 issues though:

1. You forgot to update https://github.com/zioth/dokuwiki-autolink4/blob/master/plugin.info.txt

2. If you have links with different spellings on one page, every different spelling is linked once.

For example:
```ini
[Bb]adgers?, mrweebl:badger, , once
[Mm]ushroom, mrweebl:mushroom, , once
sna+kes?, mrweebl:snake, , once
bird, mrweebl:bird, , once
```

Results in this:

![autolink4_duplicate_-links](https://user-images.githubusercontent.com/8448697/59886601-efa33d00-93bf-11e9-86c5-24ff7cfc7a10.png)

Is this on purpose, or maybe a bug?

**Comment by zioth** [comment]
plugin.info.txt: Fixed.

Linking different spellings: This was deliberate. Also, I'm pretty sure there's no way to fix it if I wanted to. Dokuwiki tells you what text matched, but it doesn't tell you which regular expression matched. This is because all regexes are combined into one for performance reasons, so there's no way to tell one from another.

**Comment by mr-floppy** [comment]
1: Thank you! :)

2: I see. Makes sense. I doubt this will become a "problem" in a real world scenario anyways. Just noticed it while testing in my testing environment.
Even if it does happen in the production environment... 2 links are still better than 200 ;)
